{{- if and .Values.minio.enabled .Values.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.minio.name }}-data
  labels:
    app.kubernetes.io/name: {{ .Values.minio.name }}
    {{- include "zeroday.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
{{- end }}
