{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zeroday.secretName" . }}
  labels:
    {{- include "zeroday.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
