{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
    app.kubernetes.io/component: postgres
    {{- include "zeroday.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
{{- end }}
