{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.minio.name }}
    app.kubernetes.io/component: minio
    {{- include "zeroday.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.minio.name }}
  ports:
    - name: api
      port: 9000
      targetPort: api
      protocol: TCP
    - name: console
      port: 9001
      targetPort: console
      protocol: TCP
{{- end }}
